### ISSUE TITLE
Suggestion on https://www.jhelvy.com/posts/2023-02-28-parameterized-pdfs-with-quarto/

### ISSUE THREAD

**Issue by bomeara** [jhelvy/jhelvy.com#8]
Thanks for this! 

Minor suggestion: using `jsonlite::serializeJSON()` and `jsonlite::unserializeJSON()` instead of `jsonlite::toJSON()` and `jsonlite::fromJSON` will preserve row and colnames in the final object.

**Comment by jhelvy** [comment]
Very cool - I did not know this! I'll update my post and the examples using this.
